### ISSUE TITLE
Assignment 8 :TODO 우측에 수정버튼과 삭제 버튼을 만든다.

### ISSUE THREAD

**Issue by JiminKim-dev** [JiminKim-dev/wanted-pre-onboarding-frontend#10]
- [x] TODO 우측에 수정버튼과 삭제 버튼을 만들어주세요
    - [x] 수정 버튼에는 data-testid="modify-button" 속성을 부여해주세요
    - [x] 삭제 버튼에는 data-testid="delete-button" 속성을 부여해주세요
```js
<li>
  <label>
    <input type="checkbox" />
    <span>TODO 1</span>
  </label>
  <button data-testid="modify-button">수정</button>
  <button data-testid="delete-button">삭제</button>
</li>
``
